### ISSUE TITLE
This is not an issue. Usage question

### ISSUE THREAD

**Issue by Satishglk** [Dilshan-H/Oblivion-Inverse#22]
Hi, I am new to this development.  I have followed instructions and successfully installed the app. I can generate the tracking link as well. I am not able to see any hits. Here is what i tried.

1. I dragged the pixel into my email and sent it to some of my own email accounts. When i received them on those accounts, i clicked on the link. [The link is http://localhost:5000/tracking-data/......) but since i am using the same computer, i assume that clicking on link will work as local host is accessible..
2. I tried to drag the link directly onto browser and i can see the link opening in browser.

Still, i dont see any hits (i refreshed the browser few times per instructions) .

I sincerely appreciate any help.

**Comment by Dilshan-H** [comment]
Hi @Satishglk,

> but since i am using the same computer, i assume that clicking on link will work as local host is accessible..

That's correct, since `localhost` is accessible on the same device, both clicking on the link and loading the embedded pixel must work.

But, the requests coming from the same session (where the active user session is in) are not logged to avoid accidentally filling up the link hits which are not intended to capture (since you don't need to capture your own access details right?). Can you please try to open the email (or you can just access the direct tracking link as well) in a new private window or in any other browser? Then it must be appear in the link hits page.
